[project]
name = "vlei-e2e"
version = "0.1.1"
description = "Add your description here"
license = { file = "LICENSE" }
readme = "README.md"
authors = [
    { name = "Kent Bull", email = "kent.bull@gleif.org" }
]
requires-python = ">=3.12.3"
dependencies = [
    "hio>=0.6.14,<0.7.0",
    "keri>=1.2.12,<1.3.0",
    "keria==0.4.0",
    "sally>=1.0.4",
    "signifypy==0.4.0",
]

[project.optional-dependencies]
test = [
    "pytest>=8.3.3,<9.0.0",  # Pin for stability; latest as of Sep 2025
    # Add other test deps if needed, e.g., pytest-mock, pytest-asyncio
]

[build-system]
requires = ["uv_build>=0.8.5,<0.9.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.uv.sources]
keria = { git = "https://github.com/GLEIF-IT/keria.git", rev = "9e2461550f373ad7bdbe7eebeaceac689cb15397" }
signifypy = { git = "https://github.com/WebOfTrust/signifypy.git", rev = "30a6806fdd9a2269b237a3e2894cab71b0920c29" }
